import Head from 'next/head'
import Image from 'next/image'
import { Banner } from '../../components/Banner'
import styles from '../../styles/Home.module.css'

export default function ContactUs() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Revorium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <Banner/>
        <h1 className={styles.title}>
          Welcome to Contact us
        </h1>

        
      </body>

      
    </div>
  )
}
