import { Typography } from '@material-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from '../components/StyledComponent'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Revorium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className=' has-text-centered ourcompany' 
          style={{ 
            justifyContent:'center',
            padding:80 ,
            background: '#2A3CA6', 
            display:'flex', 
            flex:1, 
            backgroundImage: " url('/deleteLaterMain.png')",  
            backgroundRepeat: 'no-repeat',
            backgroundSize: 'cover'
            }}>
            <div className='has-text-centered' > 
              <Typography variant='h2' component='div' style={{ color:'white', fontWeight:'400', fontFamily:'Nunito' |  'sans-serif' }}>
                BUILDING AN <span style={{ color:'#62d1cf' }}>UPRIGHT</span> WORLD <br/>WITH BLOCKCHAIN AND AI <br/>TECHNOLOGY

              </Typography>
              <div style={{ maxWidth:'100vh', marginTop:30,marginBottom:30 }}>
              <Typography variant='p' style={{ color:'white',lineHeight:2 }}>
              We focus on the future to improve the present. By developing our own technology based on Blockchain and AI, we are aiming to empower companies from different facets of the corporate world by providing personalized, accessible, effective, and practical solutions for them. We strive to eliminate  the necessary presence of the midtdlemen in your business and provide you with an opportunity to pave the road for your business the way you see fit.
              </Typography>
              </div>
              <Button color='#020283'>Let's Talk</Button>
              

              
               
            </div>
          </div>
        
        <div className='columns mt-6 mb-6'>
         
          <div className='column is-half is-offset-2'>
          <Typography variant='h4' component='div' style={{ fontWeight:'400', fontFamily:'Nunito' |  'sans-serif' }}>
            <span style={{ minWidth:4, minHeight:34, backgroundColor:'#FED576' }}></span>Special Service That We Provide <br/>
            to You
              </Typography>
          </div>
          <div className='column is-half is-offset-1 mt-4'>
            <Button backgroundColor='#020283' color='white'>See More</Button>

          </div>

        </div>

        
      </main>

      
    </div>
  )
}
