import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../../../styles/Home.module.css'

export default function SingleProduct() {
  const { query } = useRouter()
  const { name } = query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Revorium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Product {name}
        </h1>

        
      </main>

      
    </div>
  )
}
